FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    clang \
    clang-tidy \
    cmake \
    ninja-build \
    curl \
    qemu-system-arm \
    qemu-system-x86 \
    qemu-system-aarch64 \
    qemu-utils \
    graphviz && \
    rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup default stable

CMD ["bash"]

