name: Windows Runner Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]

    steps:
      - uses: actions/checkout@v4

      - name: Windows
        shell: powershell
        run: |
          "C:\Users\tomha\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Verify Cargo
        shell: powershell
        run: |
          cargo --version
          rustc --version         