name: Windows Runner Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]

    steps:
      - uses: actions/checkout@v4

      - name: Windows
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          .\windows-rust-unit-test.ps1
