name: Windows Runner Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]

    steps:
      - uses: actions/checkout@v4

      - name: Windows
        shell: powershell
        run: |
          "C:\Users\tomha\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          cargo --version          
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          .\windows-rust-unit-test.ps1
